repos:
  - repo: local
    hooks:
      - id: pyright
        name: pyright
        entry: rye run pyright
        language: system
        types: [python]
        pass_filenames: false
        require_serial: true